'use client';
import {useEffect,useState} from 'react';import {API} from '../app/lib';
const templates:Record<string,any>={
 agents:{name:'refund-agent-v1',version:'1',dispatch_type:'mock',tools:[{name:'get_order',mode:'simulated',simulation:{op:'lookup',collection:'orders',key_arg:'id'}}],behavior:{plan:[{tool:'get_order',args:{id:'$order_id'}}]}},
 worlds:{name:'ecommerce-demo',state:{orders:{o1:{id:'o1',status:'delivered',amount:49.99}},payments:{p1:{id:'p1',status:'captured',amount:49.99}},refunds:{}},metadata:{domain:'commerce'}},
 scenarios:{name:'happy-path',world:'ecommerce-demo',instruction:'Refund the duplicate payment.',variables:{order_id:'o1',payment_id:'p1'},setup:[],faults:[],assertions:[{type:'state_exists',path:'refunds.refund_0001'}],tags:['refund']},
 suites:{name:'refund-regression',scenarios:['happy-path']}
};
export function RecordEditor({kind,title,description}:{kind:string,title:string,description:string}){const [items,setItems]=useState<any[]>([]);const [text,setText]=useState(JSON.stringify(templates[kind],null,2));const [msg,setMsg]=useState('');const load=()=>fetch(`${API}/api/${kind}`).then(r=>r.json()).then(setItems).catch(()=>setItems([]));useEffect(()=>{load()},[]);async function save(){try{const body=JSON.parse(text);const r=await fetch(`${API}/api/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());setMsg('COMMITTED');load()}catch(e:any){setMsg(e.message)}}return <><div className="top"><div><div className="eyebrow">World specification / editable record</div><h1>{title}</h1><p className="muted">{description}</p></div></div><div className="split"><section className="card"><div className="sectionTitle"><h2>SPECIFICATION</h2><span>JSON / deterministic</span></div><textarea className="textarea" value={text} onChange={e=>setText(e.target.value)}/><div style={{marginTop:12}}><button className="btn" onClick={save}>Commit record</button> <span className="eyebrow" style={{marginLeft:12}}>{msg}</span></div></section><section className="card"><div className="stamp">CATALOG</div><div className="sectionTitle"><h2>REGISTERED</h2><span>{items.length} records</span></div>{items.map(x=><button className="editorItem" key={x.id} onClick={()=>setText(JSON.stringify(x.payload,null,2))}><b>{x.name}</b><div className="eyebrow" style={{marginTop:5}}>ID {String(x.id).padStart(4,'0')}</div></button>)}</section></div></>}
