import {API} from './lib';
async function summary(){try{return await fetch(`${API}/api/summary`,{cache:'no-store'}).then(r=>r.json())}catch{return {agents:0,worlds:0,scenarios:0,suites:0,runs:0}}}
async function runs(){try{return await fetch(`${API}/api/runs`,{cache:'no-store'}).then(r=>r.json())}catch{return []}}
export default async function Home(){const s=await summary();const rs=await runs();return <>
<div className="top"><div><div className="eyebrow">Adversarial testing fabric / enterprise build</div><h1>ORDEAL</h1></div><div className="eyebrow">RELEASE 1.0 / DISTRIBUTED</div></div>
<section className="hero"><div className="heroCopy"><h2>FIND THE FAILURE<br/>BEFORE IT FINDS YOU.</h2><p>Connect the agent. Compile its world. Learn behavior from real traces. Search the state space, shrink failures to minimal counterexamples, explain the causal chain, and replay the exact world across models and versions.</p></div><div className="heroInstrument"><div className="instrumentHead"><span>EXECUTION FABRIC</span><span>DISTRIBUTED</span></div><div className="orbit"><span className="orbitNode n1">AGENT</span><span className="orbitNode n2">LEDGER</span><span className="orbitNode n3">FAULT</span></div><div className="instrumentFoot">LLMS PROPOSE / THE LEDGER ESTABLISHES TRUTH</div></div></section>
<div className="flow"><span>AGENT</span><span>TOOL PROXY</span><span>WORLD COMPILER</span><span>SIMULATOR</span><span>ADVERSARY</span><span>CAUSAL</span><span>REPLAY</span></div>
<section className="section grid">{Object.entries(s).slice(0,5).map(([k,v])=><div className="card" key={k}><div className="eyebrow">{k}</div><div className="metric">{String(v)}</div></div>)}</section>
<section className="section"><div className="sectionTitle"><h2>RECENT ORDEALS</h2><span>latest execution records</span></div><div className="tableWrap"><table className="table"><thead><tr><th>RUN</th><th>STATUS</th><th>PASS RATE</th><th>TRIALS</th><th>FINGERPRINT</th></tr></thead><tbody>{rs.slice(0,8).map((r:any)=><tr key={r.id}><td>#{r.id} / {r.name}</td><td>{r.status}</td><td className={(r.payload?.pass_rate??0)>=.9?'good':'bad'}>{((r.payload?.pass_rate??0)*100).toFixed(1)}%</td><td>{r.payload?.trials?.length??0}</td><td><code>{r.payload?.run_fingerprint??'—'}</code></td></tr>)}</tbody></table></div></section>
</>}
