'use client';
import {useEffect,useState} from 'react'; import {API} from '../lib';
const sampleOpenAPI={openapi:'3.1.0',paths:{'/payments/{id}':{get:{operationId:'get_payment',summary:'Read payment',parameters:[{name:'id',in:'path'}]}},'/refunds':{post:{operationId:'create_refund',summary:'Create refund'}},'/orders/{id}':{get:{operationId:'get_order',parameters:[{name:'id',in:'path'}]}}}};
export default function Lab(){const [agents,setAgents]=useState<any[]>([]),[scenarios,setScenarios]=useState<any[]>([]),[agent,setAgent]=useState(''),[scenario,setScenario]=useState(''),[result,setResult]=useState<any>(null),[mode,setMode]=useState('fuzz'),[busy,setBusy]=useState(false);useEffect(()=>{Promise.all([fetch(`${API}/api/agents`).then(r=>r.json()),fetch(`${API}/api/scenarios`).then(r=>r.json())]).then(([a,s])=>{setAgents(a);setScenarios(s);setAgent(a[0]?.name||'');setScenario(s[0]?.name||'')})},[]);
async function fuzz(){setBusy(true);const r=await fetch(`${API}/api/lab/fuzz`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent,scenario,iterations:60,seed:7})});setResult(await r.json());setMode('fuzz');setBusy(false)}
async function compile(){setBusy(true);const r=await fetch(`${API}/api/lab/compile-world`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'compiled-commerce',openapi:sampleOpenAPI,traces:[],persist:true})});setResult(await r.json());setMode('compile');setBusy(false)}
async function shrink(){if(!result?.failure)return;setBusy(true);const f=result.failure;const r=await fetch(`${API}/api/lab/shrink`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent,scenario:f.scenario_snapshot,world:f.world_snapshot,seed:f.seed})});setResult(await r.json());setMode('shrink');setBusy(false)}
const cov=mode==='fuzz'?result?.coverage:null; return <><div className="top labTop"><div><div className="eyebrow">Autonomous adversarial discovery / build 0.3</div><h1>BREAK LAB</h1></div><div className="labSignal"><i></i>SEARCH ENGINE ARMED</div></div>
<section className="manifesto"><div className="manifestoNum">00</div><div><div className="eyebrow">OPERATING PRINCIPLE</div><h2>DON'T WRITE THE TEST.<br/><em>STATE WHAT MUST NEVER HAPPEN.</em></h2></div><p>Ordeal compiles a behavioral world, mutates its conditions, hunts for invariant violations, and reduces a discovered failure to the smallest replayable counterexample.</p></section>
<section className="labConsole"><div className="labControls"><div className="eyebrow">TARGET</div><label>AGENT<select value={agent} onChange={e=>setAgent(e.target.value)}>{agents.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label>SEED SCENARIO<select value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.map(x=><option key={x.id}>{x.name}</option>)}</select></label><div className="labActions"><button onClick={compile}>01 / COMPILE WORLD</button><button className="hot" onClick={fuzz} disabled={busy||!agent||!scenario}>02 / HUNT FAILURE</button><button onClick={shrink} disabled={!result?.failure}>03 / SHRINK</button></div></div><div className="searchField"><div className="crosshair"></div><span className="axis ax">ENVIRONMENT ENTROPY →</span><span className="axis ay">FAULT PRESSURE →</span><div className="searchCore">ORDEAL</div>{[0,1,2,3,4].map(i=><i key={i} className={`probe p${i}`}></i>)}</div></section>
{busy&&<div className="searching"><span>SEARCHING STATE SPACE</span><i></i></div>}
{result&&<section className="section"><div className="sectionTitle"><h2>{mode==='compile'?'WORLD COMPILER OUTPUT':mode==='shrink'?'MINIMAL COUNTEREXAMPLE':'ADVERSARIAL SEARCH'}</h2><span>{result.search_fingerprint||result.world?.metadata?.sources?.openapi_paths||'deterministic'}</span></div>{mode==='fuzz'&&<div className="verdictBand"><div><small>SEARCH</small><strong>{result.iterations_executed}</strong></div><div><small>FAILURE</small><strong className={result.failure_found?'bad':'good'}>{result.failure_found?'FOUND':'NONE'}</strong></div><div><small>TOOL COVERAGE</small><strong>{cov?.tool_coverage}%</strong></div><div><small>FAULT COVERAGE</small><strong>{cov?.fault_coverage}%</strong></div></div>}{mode==='shrink'&&<div className="counterexample"><span>MINIMAL REPRODUCTION</span><strong>{result.explanation}</strong><div className="failureSteps">{result.minimal_scenario?.faults?.map((f:any,i:number)=><b key={i}>{String(i+1).padStart(2,'0')} {f.tool} → {f.inject?.error||'fault'}</b>)}</div></div>}<pre className="code labCode">{JSON.stringify(result,null,2)}</pre></section>}</>}
